export const USER_ROLES = {
  WORKER: 'worker',
  SUPERVISOR: 'supervisor',
  SAFETY_OFFICER: 'safety_officer',
  ADMIN: 'admin',
} as const;

export type UserRole = typeof USER_ROLES[keyof typeof USER_ROLES];

export const ROLE_PERMISSIONS = {
  [USER_ROLES.WORKER]: {
    canViewDashboard: true,
    canSubmitChecklist: true,
    canReportHazard: true,
    canViewVideos: true,
    canViewProfile: true,
    canManageContent: false,
    canViewAnalytics: false,
    canManageUsers: false,
    canBroadcast: false,
  },
  [USER_ROLES.SUPERVISOR]: {
    canViewDashboard: true,
    canSubmitChecklist: true,
    canReportHazard: true,
    canViewVideos: true,
    canViewProfile: true,
    canViewTeamChecklists: true,
    canReviewHazards: true,
    canManageContent: false,
    canViewAnalytics: false,
    canManageUsers: false,
    canBroadcast: false,
  },
  [USER_ROLES.SAFETY_OFFICER]: {
    canViewDashboard: true,
    canSubmitChecklist: false,
    canReportHazard: true,
    canViewVideos: true,
    canViewProfile: true,
    canViewTeamChecklists: true,
    canReviewHazards: true,
    canViewSafetyReports: true,
    canManageAlerts: true,
    canBroadcast: true,
    canManageContent: false,
    canViewAnalytics: true,
    canManageUsers: false,
  },
  [USER_ROLES.ADMIN]: {
    canViewDashboard: true,
    canSubmitChecklist: false,
    canReportHazard: false,
    canViewVideos: true,
    canViewProfile: true,
    canViewTeamChecklists: true,
    canReviewHazards: true,
    canViewSafetyReports: true,
    canManageAlerts: true,
    canBroadcast: true,
    canManageContent: true,
    canViewAnalytics: true,
    canManageUsers: true,
  },
} as const;

export const MOCK_USERS = {
  worker: {
    id: 'worker_001',
    name: 'Rajesh Kumar',
    role: USER_ROLES.WORKER,
    email: 'rajesh.worker@mine.com',
    department: 'Underground Operations',
    shift: 'Morning',
  },
  supervisor: {
    id: 'supervisor_001',
    name: 'Priya Sharma',
    role: USER_ROLES.SUPERVISOR,
    email: 'priya.supervisor@mine.com',
    department: 'Underground Operations',
    team: 'Team Alpha',
  },
  safety_officer: {
    id: 'safety_001',
    name: 'Amit Singh',
    role: USER_ROLES.SAFETY_OFFICER,
    email: 'amit.safety@mine.com',
    department: 'Safety & Compliance',
    certifications: ['DGMS', 'NEBOSH'],
  },
  admin: {
    id: 'admin_001',
    name: 'Dr. Sunita Patel',
    role: USER_ROLES.ADMIN,
    email: 'sunita.admin@mine.com',
    department: 'Management',
    title: 'Safety Director',
  },
} as const;
